In [ ]:
#@title Imports
import numpy as np
import gym
import random

In [ ]:
#@title Create the Environment
env = gym.make("FrozenLake-v0")

In [ ]:
#title Get Action/State sizes
action_size = env.action_space.n
state_size = env.observation_space.n
print(action_size, state_size)

4 16


In [ ]:
# Build Q table
Q = np.zeros((state_size, action_size))
print(Q)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#@title Hyperparameters
total_episodes = 20000       # Total episodes
learning_rate = 0.7          # Learning rate
max_steps = 99               # Max steps per episode
gamma = 0.95                 # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.005            # Exponential decay rate for exploration prob

In [ ]:
def choose_action(state):
  if random.uniform(0, 1) > epsilon:
    return np.argmax(Q[state,:])  
  else:
    return env.action_space.sample()

In [ ]:
#@title Learn
def learn(reward, state, action, new_state):
  # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
  # qtable[new_state,:] : all the actions we can take from new state
  Q[state, action] = Q[state, action] + learning_rate * (reward + gamma * np.max(Q[new_state, :]) - Q[state, action])

In [ ]:
#@title Train the Agent
# List of rewards
rewards = []
epsilon = 1.0

# 2 For life or until learning is stopped
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):  
        action = choose_action(state)    

        #excute the action
        new_state, reward, done, info = env.step(action)

        learn(reward, state, action, new_state)
        
        total_rewards += reward        
        # Our new state is state
        state = new_state
        
        # If done (if we're dead) : finish episode
        if done == True: 
            break

    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)
    

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(Q)

In [ ]:
#@title Run the agent
env.reset()

for episode in range(5):
    state = env.reset()
    steps = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(Q[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            if new_state == 15:
                print("Goal reached 🏆")
            else:
                print("Aaaah ☠️")
            
            # We print the number of step it took.
            print("Number of steps", step)
            
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
  (Down)
SFFF
FHFH
FFFH
HFFG
Goal reached 🏆
Number of steps 24
****************************************************
EPISODE  1
  (Down)
SFFF
FHFH
FFFH
HFFG
Goal reached 🏆
Number of steps 31
****************************************************
EPISODE  2
  (Down)
SFFF
FHFH
FFFH
HFFG
Goal reached 🏆
Number of steps 25
****************************************************
EPISODE  3
  (Down)
SFFF
FHFH
FFFH
HFFG
Goal reached 🏆
Number of steps 92
****************************************************
EPISODE  4
  (Down)
SFFF
FHFH
FFFH
HFFG
Goal reached 🏆
Number of steps 6
